title: Emily F
logo: add a selfie later
project images:
project videos:
project repositories:
LinkedIn: https://www.linkedin.com/in/emily-l-498871115/
CodePen: https://codepen.io/waterstrider21
GitHub: https://github.com/WaterStrider21
CV: https://github.com/WaterStrider21/Portfolio/blob/54df1e964f7fc50e894d94ee376b7baf9be5adcc/EF_Resume_72026.docx.pdf
theme: jekyll-theme-minimal

