title: Emily F
logo: add a selfie later
project images:

project videos:
https://www.youtube.com/watch?v=zy6yjjl9pjU
https://youtu.be/bypdMDqcGKM

project repositories:
Ecommerce: https://github.com/WaterStrider21/D287_Emily-s_Wagons
Simple Timer: https://github.com/WaterStrider21/Simple-Timer

LinkedIn: https://www.linkedin.com/in/emily-l-498871115/
img: https://github.com/WaterStrider21/Portfolio/blob/main/LI-Logo.png

CodePen: https://codepen.io/waterstrider21
img: https://github.com/WaterStrider21/Portfolio/blob/main/CodePen_logo.png

GitHub: https://github.com/WaterStrider21
img: https://github.com/WaterStrider21/Portfolio/blob/main/GitHub_Lockup_White_Clearspace.png

CV: https://github.com/WaterStrider21/Portfolio/blob/54df1e964f7fc50e894d94ee376b7baf9be5adcc/EF_Resume_72026.docx.pdf
theme: jekyll-theme-minimal
